### ISSUE TITLE
熟悉的readme开源，熟悉的阿里

### ISSUE THREAD

**Issue by balala8** [ali-vilab/In-Context-LoRA#2]
发现是个readme开源，刚想说是不是阿里的，一看果然是！

**Comment by huanglianghua** [comment]
@balala8 训练、推理代码已开源（可以直接使用ai-toolkit），示例训练代码和配置文件已开源。部分任务的模型参数也会开源

**Comment by FFFFFFpy** [comment]
不懂就问，这和普通炼个lora有什么区别？也就是数据集处理方法有点与众不同？
