### ISSUE TITLE
The maximum number of tokens is 77？

### ISSUE THREAD

**Issue by jxy0** [ali-vilab/In-Context-LoRA#34]
Hello, when I use the model, I encounter the problem of the maximum number of tokens 77, and the model will directly cut off the content behind my token. Is this normal? Even the official sample did not generate the image correctly because some tokens were truncated

**Comment by Thorazineo** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by LeileiCao** [comment]
How did you solve this issue?

**Comment by zjYao36** [comment]
I have same queation
