### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by moeinheidari7829** [ali-vilab/In-Context-LoRA#4]
Dear authors, 

thank you for releasing the code of your work. The code folder of your repo is empty, can you please clarify on the code release time and also how your code is different from the ai-toolkit code?

**Comment by huanglianghua** [comment]
> Dear authors, 
> 
> 
> 
> thank you for releasing the code of your work. The code folder of your repo is empty, can you please clarify on the code release time and also how your code is different from the ai-toolkit code?

Hi, we directly use ai-toolkit for training our models, and there is no need for further code. We have released sample training configuration and data, please refer to the Getting Started on how to train.
