### ISSUE TITLE
Will we have the comfyui version in the future?

### ISSUE THREAD

**Issue by Pancat009** [ali-vilab/In-Context-LoRA#6]
would be glad to know if we have any plan for enabling this feature on comfyui

**Comment by huanglianghua** [comment]
> would be glad to know if we have any plan for enabling this feature on comfyui

Yes, we are currently working on this.

**Comment by huanglianghua** [comment]
> would be glad to know if we have any plan for enabling this feature on comfyui

10 pretrained models and an example ComfyUI workflow released.
