### ISSUE TITLE
film-storyboard.safetensors无法打开下载链接

### ISSUE THREAD

**Issue by chenfengzi01** [ali-vilab/In-Context-LoRA#7]
film-storyboard.safetensors无法打开hugging face下载链接

**Comment by huanglianghua** [comment]
> film-storyboard.safetensors无法打开hugging face下载链接

Fixed. The download link for film-storyboard.safetensors is: https://huggingface.co/ali-vilab/In-Context-LoRA/blob/main/film-storyboard.safetensors

**Comment by qqphung** [comment]
hi @huanglianghua, how to inference with your checkpoint?

**Comment by huanglianghua** [comment]
> hi @huanglianghua, how to inference with your checkpoint?

Hi @qqphung, you can use ComfyUI for inference—just put the checkpoint files under `ComfyUI/models/loras` and drag and drop the "workflow/film-storyboard.json" file onto the ComfyUI interface.

You can also use diffusers for inference, the code will be like:

```python
from diffusers import FluxPipeline

your_lora_checkpoint_file = "./film-storyboard.safetensors"
prompt = "[your prompt]"

pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16)
pipe.load_lora_weights(your_lora_checkpoint_file)
pipe = pipe.to(torch.device("cuda:0"))
pipe.enable_lora()

out = pipe(
    prompt=prompt,
    guidance_scale=3.5,
    height=1536,
    width=1024,
    num_inference_steps=50,
).images[0]
out.save("image.png")
```
