### ISSUE TITLE
How to use ImageCondition

### ISSUE THREAD

**Issue by bezorro** [ali-vilab/In-Context-LoRA#8]
Great work! I’ve learned a lot from it. At the same time, I think generating with ImageCondition could make this work even more impactful.

I saw you mentioned using SDEdit for this, so I tried it briefly but didn’t have much success. Could you explain a bit more?

Taking a portrait illustration as an example, my approach was to concatenate a blank image to the right of [Image1] and then perform inpainting on the whole image with a denoising strength of 0.5-0.8. However, the result left the right side blank, which I believe is due to the influence of the white area.

Could you guide me through the specific steps for implementing ImageCondition, as well as other possible solutions like IP-Adapter, Textual Inversion, etc.? Thank you very much!

**Comment by huanglianghua** [comment]
> Great work! I’ve learned a lot from it. At the same time, I think generating with ImageCondition could make this work even more impactful.
> 
> I saw you mentioned using SDEdit for this, so I tried it briefly but didn’t have much success. Could you explain a bit more?
> 
> Taking a portrait illustration as an example, my approach was to concatenate a blank image to the right of [Image1] and then perform inpainting on the whole image with a denoising strength of 0.5-0.8. However, the result left the right side blank, which I believe is due to the influence of the white area.
> 
> Could you guide me through the specific steps for implementing ImageCondition, as well as other possible solutions like IP-Adapter, Textual Inversion, etc.? Thank you very much!

Thanks for your interest! We’ll be uploading a ComfyUI workflow to help with image conditioning. Essentially, we use the InpaintModelConditioning node in ComfyUI to handle this.

**Comment by wanglaofei** [comment]
It's  an interesting work, and the results are amazing good. Is there any image-condition workflow to reference? Thanks for your time!

**Comment by zoezhou1999** [comment]
Hi @huanglianghua 
Is it possible to share ComfyUI workflow that supports image conditioning? I am new to ComfyUI, which makes me a bit confused after reading your hints.
Thank you very much!
